package com.inkspire.ebookreader.ui.home.explore.common

val truyenFullCategories = listOf(
    "Tiên Hiệp" to "tien-hiep",
    "Kiếm Hiệp" to "kiem-hiep",
    "Ngôn Tình" to "ngon-tinh",
    "Đam Mỹ" to "dam-my",
    "Quan Trường" to "quan-truong",
    "Võng Du" to "vong-du",
    "Khoa Huyễn" to "khoa-huyen",
    "Hệ Thống" to "he-thong",
    "Huyền Huyễn" to "huyen-huyen",
    "Dị Giới" to "di-gioi",
    "Dị Năng" to "di-nang",
    "Quân Sự" to "quan-su",
    "Lịch Sử" to "lich-su",
    "Xuyên Không" to "xuyen-khong",
    "Xuyên Nhanh" to "xuyen-nhanh",
    "Trọng Sinh" to "trong-sinh",
    "Trinh Thám" to "trinh-tham",
    "Thám Hiểm" to "tham-hiem",
    "Linh Dị" to "linh-di",
    "Ngược" to "nguoc",
    "Sủng" to "sung",
    "Cung Đấu" to "cung-dau",
    "Nữ Cường" to "nu-cuong",
    "Gia Đấu" to "gia-dau",
    "Đông Phương" to "dong-phuong",
    "Đô Thị" to "do-thi",
    "Bách Hợp" to "bach-hop",
    "Hài Hước" to "hai-huoc",
    "Điền Văn" to "dien-van",
    "Cổ Đại" to "co-dai",
    "Mạt Thế" to "mat-the",
    "Truyện Teen" to "truyen-teen",
    "Phương Tây" to "phuong-tay",
    "Nữ Phụ" to "nu-phu",
    "Light Novel" to "light-novel",
    "Đoản Văn" to "doan-van",
    "Khác" to "khac"
)