package com.inkspire.ebookreader.ui.home.explore.common

enum class TruyenFullCategory(
    override val displayName: String,
    override val slug: String
) : WebsiteCategory {
    TIEN_HIEP("Tiên Hiệp", "tien-hiep"),
    KIEM_HIEP("Kiếm Hiệp", "kiem-hiep"),
    NGON_TINH("Ngôn Tình", "ngon-tinh"),
    DAM_MY("Đam Mỹ", "dam-my"),
    QUAN_TRUONG("Quan Trường", "quan-truong"),
    VONG_DU("Võng Du", "vong-du"),
    KHOA_HUYEN("Khoa Huyễn", "khoa-huyen"),
    HE_THONG("Hệ Thống", "he-thong"),
    HUYEN_HUYEN("Huyền Huyễn", "huyen-huyen"),
    DI_GIOI("Dị Giới", "di-gioi"),
    DI_NANG("Dị Năng", "di-nang"),
    QUAN_SU("Quân Sự", "quan-su"),
    LICH_SU("Lịch Sử", "lich-su"),
    XUYEN_KHONG("Xuyên Không", "xuyen-khong"),
    XUYEN_NHANH("Xuyên Nhanh", "xuyen-nhanh"),
    TRONG_SINH("Trọng Sinh", "trong-sinh"),
    TRINH_THAM("Trinh Thám", "trinh-tham"),
    THAM_HIEM("Thám Hiểm", "tham-hiem"),
    LINH_DI("Linh Dị", "linh-di"),
    NGUOC("Ngược", "nguoc"),
    SUNG("Sủng", "sung"),
    CUNG_DAU("Cung Đấu", "cung-dau"),
    NU_CUONG("Nữ Cường", "nu-cuong"),
    GIA_DAU("Gia Đấu", "gia-dau"),
    DONG_PHUONG("Đông Phương", "dong-phuong"),
    DO_THI("Đô Thị", "do-thi"),
    BACH_HOP("Bách Hợp", "bach-hop"),
    HAI_HUOC("Hài Hước", "hai-huoc"),
    DIEN_VAN("Điền Văn", "dien-van"),
    CO_DAI("Cổ Đại", "co-dai"),
    MAT_THE("Mạt Thế", "mat-the"),
    TRUYEN_TEEN("Truyện Teen", "truyen-teen"),
    PHUONG_TAY("Phương Tây", "phuong-tay"),
    NU_PHU("Nữ Phụ", "nu-phu"),
    LIGHT_NOVEL("Light Novel", "light-novel"),
    DOAN_VAN("Đoản Văn", "doan-van"),
    KHAC("Khác", "khac");
}